import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import styles from '@/styles/Home.module.css'
import CartNavBar from './components/nav-bar/cart_nav_bar'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/logo.png" />
      </Head>
      <main>
<CartNavBar />
      </main>
    </>
  )
}
