import Seccion from "@/components/Seccion"




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./assets/logo.png" />
      </Head>
      <main>
  <Seccion />
      </main>
    </>
  )
}
